workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      
      - name: Analyze code
        script: flutter analyze
      
      - name: Build APK
        script: flutter build apk --release
    
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    
    publishing:
      email:
        recipients:
          - your-email@example.com
